# Generated by Django 2.2 on 2022-06-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_owner_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
