# Generated by Django 2.2 on 2022-06-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_owner_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='tenat_name',
            new_name='owner_name',
        ),
    ]
