# Generated by Django 2.2 on 2022-06-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20220628_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='from_date',
        ),
    ]
